set test "api-main"

set testsuite {
    "arm-linux-gnueabi" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = R0"
        "main_argv :: in out u32 = R1"
        "main_result :: out u32 = R0"
    }
    "arm-linux-androideabi" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = R0"
        "main_argv :: in out u32 = R1"
        "main_result :: out u32 = R0"
    }
    "i686-w64-mingw32" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = mem32?ESP + 0x4:32, el?:u32"
        "main_argv :: in out u32 = mem32?ESP + 0x8:32, el?:u32"
        "main_result :: out u32 = EAX"
    }
    "x86_64-w64-mingw32" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = RCX"
        "main_argv :: in out u64 = RDX"
        "main_result :: out u32 = RAX"
    }
    "x86_64-linux-gnu" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = RDI"
        "main_argv :: in out u64 = RSI"
        "main_result :: out u32 = RAX"
    }
    "x86-linux-gnu" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = mem32?ESP + 0x4:32, el?:u32"
        "main_argv :: in out u32 = mem32?ESP + 0x8:32, el?:u32"
        "main_result :: out u32 = EAX"
    }
}


foreach {target lines} $testsuite {
    set file "$bindir/$target-echo"
    foreach line $lines {
        spawn bap "$file" -d
        expect {
            $line {pass "$test <$line> in $target"}
            default {
                if [file exists $file ] {
                    fail "$test <$line> $target"
                } else {
                    untested "$test $target"
                }
            }
        }
    }
}
