set test "api-main"

set testsuite {
    "arm-linux-gnueabi" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = R0"
        "main_argv :: in out u32 = R1"
        "main_result :: out u32 = R0"
    }
    "arm-linux-androideabi" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = R0"
        "main_argv :: in out u32 = R1"
        "main_result :: out u32 = R0"
    }
    "i686-w64-mingw32" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = mem[ESP + 4, el]:u32"
        "main_argv :: in out u32 = mem[ESP + 8, el]:u32"
        "main_result :: out u32 = EAX"
    }
    "x86_64-w64-mingw32" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = RCX"
        "main_argv :: in out u64 = RDX"
        "main_result :: out u32 = RAX"
    }
    "x86_64-linux-gnu" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = RDI"
        "main_argv :: in out u64 = RSI"
        "main_result :: out u32 = RAX"
    }
    "x86-linux-gnu" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = mem[ESP + 4, el]:u32"
        "main_argv :: in out u32 = mem[ESP + 8, el]:u32"
        "main_result :: out u32 = EAX"
    }
    "mips-linux-gnu" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = A0"
        "main_argv :: in out u32 = A1"
        "main_result :: out u32 = V0"
    }
    "mips64-linux-gnueabi" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u64 = A0"
        "main_argv :: in out u64 = A1"
        "main_result :: out u64 = V0"
    }
    "powerpc32-linux-gnu" {
        "sub main(main_argc, main_argv, main_result)"
        "main_argc :: in u32 = R3"
        "main_argv :: in out u32 = R4"
        "main_result :: out u32 = R3"
    }
}

foreach {target lines} $testsuite {
    set file "$bindir/$target-echo"
    find_all $file bir $lines $test
}
