set test "byteweight"

foreach file [find "bin" "*-echo"] {
    match $file bir "" {
        "sub .*print_strings" { pass "$test $file"}
        default {
            if [string match "*-*-gnueabihf-*" $file] {
                note "signatures do not handle gnueabihf mode"
                xfail "$test in $file"
            } else {
                fail "$test in $file"
            }
        }
    }
}
