set test "collators"
setup-logs $test

set collator "callgraph"
set base bin/arm-linux-gnueabi-echo

match_output bap "compare $collator $base $base" {
    "the same callgraph" {pass "base is equal to base"}
    default {fail "base is equal to base"}
}

set echos [glob bin/*-echo]

match_all bap "compare $collator $base $echos" {
    "is not different" "base is in the set"
    "Found 9 versions that are different" "all other are different"
}
