set test "config"

set file "$bindir/x86-linux-gnu-echo"

set etc [exec opam config var etc]
set confdir "$etc/bap/print"
set conf_file $confdir/config
exec mkdir -p $confdir
exec echo "symbol=print_strings" > $conf_file

spawn bap $file -d

expect {
    "sub main"   {close; wait; fail "$test: main is unexpected because not set in conf file"}
    "sub print_strings" {close; wait; pass "$test for reading parameters from conf file"}
    default {wait; fail "no output or wrong one is for $test"}
}

spawn bap $file -d --print-symbol=main

expect {
    "sub print_strings" {close; wait; fail "$test: print_strings is unexpected"}
    "sub main"   {close; wait; pass "$test for overriding parameters in conf file"}
    default {wait; fail "no output or wrong one is for $test"}
}

exec rm -r $confdir
