set test "dynamic-libraries"

set dyn_dir "dyn"

set cases {
    "x86-coff-libvlc_dll" "libvlc_printerr" "libvlc_add_intf"
    "x86_64-macho_dylib" "_printf" "_my_print"
    "x86_64-elf_so" "my_print" ""
}
# elf test checks that file just loadable - since we still don't manage with plt/got sections

foreach {file sym caller} $cases {
    set file "$dyn_dir/$file"
    spawn bap $file --brancher=relocatable -d --rooter=internal --print-symbol=$sym
    expect {
        "sub $sym" {pass "$test test for sub $sym in $file"}
        default {fail "$test test: no sub $sym in $file"}
    }

    if {[string length $caller] != 0} {
        spawn bap $file --brancher=relocatable -d --rooter=internal --print-symbol=$caller
        expect {
            "call @$sym" {pass "$test test for call @$sym in $file"}
            default {fail "$test test: no call of @$sym in $file"}
        }
    }
}
