set test "improper_feed"

proc touch {data} {
    set file [exec mktemp]
    if {[string length $data] != 0} {
        exec echo $data > $file
    }
    return $file
}

set files {
  "empty file"    "file is empty" ""
  "random data"   "File format is not supported" "Hello, world"
  "truncated elf" "File format is not supported" "\x7f\x45\x4c\x46\x02\x01\x01"
}

foreach {msg expected data} $files {
    set file [touch $data]
    spawn bap $file -d
    set status [lindex [wait] 3]
    if {$status != 0} {
        expect {
            $expected {pass "$test for $msg"}
            default {fail "no diagnostic/wrong messages in $test for $msg"}
        }
    } else {fail "unexpected zero exit status in $test for $msg"}
    exec rm $file
}
