set test "improper_feed"

proc touch {data} {
    set file [exec mktemp]
    if {[string length $data] != 0} {
        exec echo $data > $file
    }
    return $file
}

set files {
  "empty file"    "File corrupted" ""
  "random data"   "File format is not supported" "Hello, world"
  "truncated elf" "File format is not supported" "\x7f\x45\x4c\x46\x02\x01\x01"
}

foreach {msg expected data} $files {
    set file [touch $data]
    with-exit-code $msg "$file -d" $expected 1
}
