set test "kernel-modules"

set file "ko/arm-can-bcm.ko"

# Test checks that next external symbols are represented as synthetic subroutines
# and are called

set cases {
    "ko/arm-can-bcm.ko" {
        "sub kfree"
        "sub memcpy(memcpy_dst, memcpy_src, memcpy_n, memcpy_result)"
        "sub sprintf(sprintf_str, sprintf_format, sprintf_result)"
        "call @kfree"
        "call @memcpy"
        "call @sprintf"
    }
}

foreach {file strs} $cases {
    find_all $file bir $strs $test "--no-byteweight"
}
