set test "llvm-base"
setup-logs $test

set testsuite {
    "arm-linux-gnueabi"     main 614
    "arm-linux-androideabi" main 668
    "i686-w64-mingw32"      main 15c7
    "x86_64-w64-mingw32"    main 25a0
    "x86_64-linux-gnu"      main 76b
    "x86-linux-gnu"         main 5a4
    "x86_64-macho"          main e50
}

set print_opts {
    --print-symbol-format=name
    --print-symbol-format=addr
}

set new_base 42

foreach {target name addr0} $testsuite {
    set file "$bindir/$target-echo"
    set msg "$test for base=$new_base in $file for $name"
    set addr [format %x [expr "0x$addr0" + $new_base ]]
    set opts [subst {--loader=llvm --llvm-base=$new_base}]
    set opts [concat $opts [join $print_opts " "]]
    match $file symbols $opts {
        "$name $addr" {pass "$test for $name $addr"}
        default {fail "$test for $name $addr"}
    }
}
