set test "macho loader"

# Check that relocataions from dysymtab are read correctly
# both for little and big endian files

set cases {
    "ko/powerpc-xnu-kext" "ref-external 45480 _abort"
    "ko/x86_64-xnu-kext" "ref-external 18439 _memcmp"
}

foreach {file expected} $cases {
    spawn bap $file --dump=ogre
    expect {
        $expected {close; wait; pass "$test for $file"}
        default {wait; fail "$test for $file"}
    }
}
