set test "macho loader"

# Check that relocations from dysymtab are read correctly
# both for little and big endian files

set cases {
    "ko/powerpc-xnu-kext" "external-reference 45480 _abort"
    "ko/x86_64-xnu-kext" "external-reference 18439 _memcmp"
}

foreach {file expected} $cases {
    match $file ogre "--no-objdump --no-radare2" {
        $expected {pass "$test for $file"}
        default {fail "$test for $file"}
    }
}
