set test "object files"

set obj_dir "obj"

set subs {
    "sum_external"
    "sum_internal_1"
    "sum_internal_2"
    "sum_internal_3"
}

set prefixes {"sub " "call @" }

proc expected_of_file {file subs prefixes} {
    set x {}
    foreach {sub} $subs {
        foreach {pref} $prefixes {
            if { [string match "*i686*" $file] || [string match "*mac*" $file] } {
                set suf "_"
            } else {
                set suf ""
            }
            lappend x "$pref$suf$sub"
        }
    }
    return $x
}


foreach {file} [exec ls $obj_dir] {
    set file "$obj_dir/$file"
    set expected [expected_of_file $file $subs $prefixes]
    find_all $file bir $expected [concat $test $file]
}
