set test "plugins"
setup-logs $test

set plugins [exec bap "list" "plugins" | cut "-d " -f3]

exec bap --version




set log [split [get-log] "\n"]

foreach plugin $plugins {
    set found 0
    foreach line $log {
        if [string match "*Loaded $plugin*" $line] {
            set found 1
            break
        }
    }

    if {$found} {
        pass "$plugin was loaded"
    } else {
        fail "$plugin wasn't loaded"
    }
}
