set test "run"

set expected {
hello
cruel
world
we
not
are
some
thine
the
be
course
}


puts "running $test"

set base_opts {
    --run-argv=hello,cruel,world
    --primus-lisp-type-check
    --run
}

set systems {
    bap:stubbed-executor
    bap:legacy-main
}


set mips32 "mips-linux-gnu-echo"
set mips64 "mips64-linux-gnueabi-echo"
set powerpc "powerpc32-linux-gnu-echo"

set bins [subst {
    "arm-linux-gnueabi-echo"
    "x86-linux-gnu-echo"
    "x86_64-linux-gnu-echo"
    "$mips32"
    "$mips64"
    "$powerpc"
}]

set output [join $expected ".*"]

foreach bin $bins {
    set opts $base_opts
    if { $bin == "$powerpc" } {
        lappend opts "--api-path=api/powerpc"
    }
    foreach system $systems {
        set full_opts $opts
        lappend full_opts "--run-system=$system"
        lappend full_opts "--read-symbols-from data/$bin.symbols"

        match "bin/$bin" "" [join $full_opts " "] {
            "ill-typed" { fail "program is ill-typed" }
            "$output" { pass "$test $system $bin outputs everything" }
            default { fail "got incomplete output from $bin with $system"}
        }

    }
}
