set test "run"

set outputs {
hello
cruel
world
we
not
are
some
thine
the
be
course
}

puts "running $test"

set base_opts {
    --run-argv='hello,cruel,world'
    --run
    --primus-lisp-type-check
}

set mips32 "mips-linux-gnu-echo"
set mips64 "mips64-linux-gnueabi-echo"
set powerpc "powerpc32-linux-gnu-echo"

set bins [subst {
    "arm-linux-gnueabi-echo"
    "x86-linux-gnu-echo"
    "x86_64-linux-gnu-echo"
    "$mips32"
    "$mips64"
    "$powerpc"
}]

foreach output $outputs {
    foreach bin $bins {
        set opts $base_opts
        if { $bin == "$powerpc" } {
            lappend opts "--api-path=api/powerpc"
        }

        eval spawn bap "bin/$bin" --read-symbols-from "data/$bin.symbols" [join $opts " "]
        expect {
            "ill-typed" {close; wait; fail "program is ill-typed" }
            $output {close; wait; pass "$test $bin outputs $output" }
            timeout {wait; fail "got timeout"}
            default {wait; fail "missing '$output' in output of $bin"}
        }
    }
}
