set test "symexec"
setup-logs $test

puts "running $test"

set base_opts {
    --run
    --run-system=bap:symbolic-executor
    --primus-lisp-load=symbolic-stdio,posix
    --primus-symbolic-executor-cutoff=16
    --run-in-isolation
}

foreach bin [find "bin" "*-symexec-*"] {
    set opts $base_opts
    if [ string match "*powerpc*" $bin ] {
        lappend opts "--api-path=api/powerpc"
    }

    if {[string match "*mingw*" $bin ] || [string match "*mips*" $bin ]} {
        continue
    }

    set symbols [file join data [file tail $bin]]

    eval spawn bap "$bin" [join $opts " "] --read-symbols-from "$symbols.symbols"
    set timeout 240
    expect {
        "access" {close; exec kill [exp_pid]; pass "$bin was hacked!" }
        timeout {close; exec kill [exp_pid]; fail "$bin run out of time."}
        eof {wait; fail "$bin withhold the attack."}
    }
}
