set test "propagate taint"
set regs {ZF}
set bir_attrs {tainted-reg tainted-regs visited}

set opts "-d --pass=propagate-taint"
foreach reg $regs {lappend opts "--taint-reg=$reg"}
foreach attr $bir_attrs {lappend opts "--print-bir-attr=$attr"}

foreach attr $bir_attrs {
    foreach-binary {file *} "bap $opts" {
        ".$attr" {pass "$test $attr in $file"}
        default  {fail "$test $attr in $file"}
    }
}
