set test "x86-prefix"
setup-logs $test

set suite {
    {0xf3,0x89,0xc3}                0x3 {mov. %eax, %ebx}
    {0xf3,0xf2,0xf3,0x89,0xc3}      0x5 {mov. %eax, %ebx}
    {0xf3,0xf2,0xf3,0x48,0x89,0xc3} 0x6 {mov. %rax, %rbx}
}

set regexps {}
set codes   {}
foreach {code size asm} $suite {
    lappend codes $code
    lappend regexps "$size.*$asm"
}

set opts "--show-size --show-insn=asm $codes"

match_until bap-mc $opts "$test" $regexps
