unset -nocomplain suite

set suite(x86-64) {
    {movabsq %rax, 0x4} {*\[0x4:64, el\]*}
    {movq %rax, (%rbp)} {*\[RBP, el\]*}
    {movq %rax, (%rbp,%rdx)} {*\[RBP + RDX, el\]*}
    {movq %rax, (%rbp,%rdx,2)} {*\[RBP + (RDX << 0x1:2), el\]*}
    {movq %rax, (%rbp,%rdx,4)} {*\[RBP + (RDX << 0x2:2), el\]*}
    {movq %rax, (%rbp,%rdx,8)} {*\[RBP + (RDX << 0x3:2), el\]*}
    {movq %rax, 0x4(%rbp)} {*\[RBP + 0x4:64, el\]*}
    {movq %rax, 0x4(%rbp,%rdx)} {*\[(RBP + RDX) + 0x4:64, el\]*}
    {movq %rax, 0x4(%rbp,%rdx,2)} {*\[(RBP + (RDX << 0x1:2)) + 0x4:64, el\]*}
    {movq %rax, 0x4(%rbp,%rdx,4)} {*\[(RBP + (RDX << 0x2:2)) + 0x4:64, el\]*}
    {movq %rax, 0x4(%rbp,%rdx,8)} {*\[(RBP + (RDX << 0x3:2)) + 0x4:64, el\]*}
    {movq %rdi, (,%rax)} {*\[RAX, el\]*}
    {movq %rdi, (,%rax,2)} {*\[RAX << 0x1:2, el\]*}
    {movq %rdi, (,%rax,4)} {*\[RAX << 0x2:2, el\]*}
    {movq %rdi, (,%rax,8)} {*\[RAX << 0x3:2, el\]*}
    {movq %rdi, 0x4(,%rax)} {*\[RAX + 0x4:64, el\]*}
    {movq %rdi, 0x4(,%rax,2)} {*\[(RAX << 0x1:2) + 0x4:64, el\]*}
    {movq %rdi, 0x4(,%rax,4)} {*\[(RAX << 0x2:2) + 0x4:64, el\]*}
    {movq %rdi, 0x4(,%rax,8)} {*\[(RAX << 0x3:2) + 0x4:64, el\]*}
    {movq %rdi, (%rip)} {*\[0x7:64, el\]*}
    {movq %rdi, 0x4(%rip)} {*\[0x7:64 + 0x4:64, el\]*}

    {movq %rax, %fs:(%rbp)} {*\[FS_BASE + RBP, el\]*}
    {movq %rax, %fs:(%rbp,%rdx)} {*\[FS_BASE + (RBP + RDX), el\]*}
    {movq %rax, %fs:(%rbp,%rdx,2)} {*\[FS_BASE + (RBP + (RDX << 0x1:2)), el\]*}
    {movq %rax, %fs:(%rbp,%rdx,4)} {*\[FS_BASE + (RBP + (RDX << 0x2:2)), el\]*}
    {movq %rax, %fs:(%rbp,%rdx,8)} {*\[FS_BASE + (RBP + (RDX << 0x3:2)), el\]*}
    {movq %rax, %fs:0x4(%rbp)} {*\[FS_BASE + (RBP + 0x4:64), el\]*}
    {movq %rax, %fs:0x4(%rbp,%rdx)} {*\[FS_BASE + ((RBP + RDX) + 0x4:64), el\]*}
    {movq %rax, %fs:0x4(%rbp,%rdx,2)} {*\[FS_BASE + ((RBP + (RDX << 0x1:2)) + 0x4:64), el\]*}
    {movq %rax, %fs:0x4(%rbp,%rdx,4)} {*\[FS_BASE + ((RBP + (RDX << 0x2:2)) + 0x4:64), el\]*}
    {movq %rax, %fs:0x4(%rbp,%rdx,8)} {*\[FS_BASE + ((RBP + (RDX << 0x3:2)) + 0x4:64), el\]*}
    {movq %rdi, %fs:(,%rax)} {*\[FS_BASE + RAX, el\]*}
    {movq %rdi, %fs:(,%rax,2)} {*\[FS_BASE + (RAX << 0x1:2), el\]*}
    {movq %rdi, %fs:(,%rax,4)} {*\[FS_BASE + (RAX << 0x2:2), el\]*}
    {movq %rdi, %fs:(,%rax,8)} {*\[FS_BASE + (RAX << 0x3:2), el\]*}
    {movq %rdi, %fs:0x4(,%rax)} {*\[FS_BASE + (RAX + 0x4:64), el\]*}
    {movq %rdi, %fs:0x4(,%rax,2)} {*\[FS_BASE + ((RAX << 0x1:2) + 0x4:64), el\]*}
    {movq %rdi, %fs:0x4(,%rax,4)} {*\[FS_BASE + ((RAX << 0x2:2) + 0x4:64), el\]*}
    {movq %rdi, %fs:0x4(,%rax,8)} {*\[FS_BASE + ((RAX << 0x3:2) + 0x4:64), el\]*}
    {movq %rdi, %fs:(%rip)} {*\[FS_BASE + 0x8:64, el\]*}
    {movq %rdi, %fs:0x4(%rip)} {*\[FS_BASE + (0x8:64 + 0x4:64), el\]*}

    {movq %rax, %gs:(%rbp)} {*\[GS_BASE + RBP, el\]*}
    {movq %rax, %gs:(%rbp,%rdx)} {*\[GS_BASE + (RBP + RDX), el\]*}
    {movq %rax, %gs:(%rbp,%rdx,2)} {*\[GS_BASE + (RBP + (RDX << 0x1:2)), el\]*}
    {movq %rax, %gs:(%rbp,%rdx,4)} {*\[GS_BASE + (RBP + (RDX << 0x2:2)), el\]*}
    {movq %rax, %gs:(%rbp,%rdx,8)} {*\[GS_BASE + (RBP + (RDX << 0x3:2)), el\]*}
    {movq %rax, %gs:0x4(%rbp)} {*\[GS_BASE + (RBP + 0x4:64), el\]*}
    {movq %rax, %gs:0x4(%rbp,%rdx)} {*\[GS_BASE + ((RBP + RDX) + 0x4:64), el\]*}
    {movq %rax, %gs:0x4(%rbp,%rdx,2)} {*\[GS_BASE + ((RBP + (RDX << 0x1:2)) + 0x4:64), el\]*}
    {movq %rax, %gs:0x4(%rbp,%rdx,4)} {*\[GS_BASE + ((RBP + (RDX << 0x2:2)) + 0x4:64), el\]*}
    {movq %rax, %gs:0x4(%rbp,%rdx,8)} {*\[GS_BASE + ((RBP + (RDX << 0x3:2)) + 0x4:64), el\]*}
    {movq %rdi, %gs:(,%rax)} {*\[GS_BASE + RAX, el\]*}
    {movq %rdi, %gs:(,%rax,2)} {*\[GS_BASE + (RAX << 0x1:2), el\]*}
    {movq %rdi, %gs:(,%rax,4)} {*\[GS_BASE + (RAX << 0x2:2), el\]*}
    {movq %rdi, %gs:(,%rax,8)} {*\[GS_BASE + (RAX << 0x3:2), el\]*}
    {movq %rdi, %gs:0x4(,%rax)} {*\[GS_BASE + (RAX + 0x4:64), el\]*}
    {movq %rdi, %gs:0x4(,%rax,2)} {*\[GS_BASE + ((RAX << 0x1:2) + 0x4:64), el\]*}
    {movq %rdi, %gs:0x4(,%rax,4)} {*\[GS_BASE + ((RAX << 0x2:2) + 0x4:64), el\]*}
    {movq %rdi, %gs:0x4(,%rax,8)} {*\[GS_BASE + ((RAX << 0x3:2) + 0x4:64), el\]*}
    {movq %rdi, %gs:(%rip)} {*\[GS_BASE + 0x8:64, el\]*}
    {movq %rdi, %gs:0x4(%rip)} {*\[GS_BASE + (0x8:64 + 0x4:64), el\]*}

    {movq %rax, %cs:(%rbp)} {*\[RBP, el\]*}
    {movq %rax, %cs:(%rbp,%rdx)} {*\[RBP + RDX, el\]*}
    {movq %rax, %cs:(%rbp,%rdx,2)} {*\[RBP + (RDX << 0x1:2), el\]*}
    {movq %rax, %cs:(%rbp,%rdx,4)} {*\[RBP + (RDX << 0x2:2), el\]*}
    {movq %rax, %cs:(%rbp,%rdx,8)} {*\[RBP + (RDX << 0x3:2), el\]*}
    {movq %rax, %cs:0x4(%rbp)} {*\[RBP + 0x4:64, el\]*}
    {movq %rax, %cs:0x4(%rbp,%rdx)} {*\[(RBP + RDX) + 0x4:64, el\]*}
    {movq %rax, %cs:0x4(%rbp,%rdx,2)} {*\[(RBP + (RDX << 0x1:2)) + 0x4:64, el\]*}
    {movq %rax, %cs:0x4(%rbp,%rdx,4)} {*\[(RBP + (RDX << 0x2:2)) + 0x4:64, el\]*}
    {movq %rax, %cs:0x4(%rbp,%rdx,8)} {*\[(RBP + (RDX << 0x3:2)) + 0x4:64, el\]*}
    {movq %rdi, %cs:(,%rax)} {*\[RAX, el\]*}
    {movq %rdi, %cs:(,%rax,2)} {*\[RAX << 0x1:2, el\]*}
    {movq %rdi, %cs:(,%rax,4)} {*\[RAX << 0x2:2, el\]*}
    {movq %rdi, %cs:(,%rax,8)} {*\[RAX << 0x3:2, el\]*}
    {movq %rdi, %cs:0x4(,%rax)} {*\[RAX + 0x4:64, el\]*}
    {movq %rdi, %cs:0x4(,%rax,2)} {*\[(RAX << 0x1:2) + 0x4:64, el\]*}
    {movq %rdi, %cs:0x4(,%rax,4)} {*\[(RAX << 0x2:2) + 0x4:64, el\]*}
    {movq %rdi, %cs:0x4(,%rax,8)} {*\[(RAX << 0x3:2) + 0x4:64, el\]*}
    {movq %rdi, %cs:(%rip)} {*\[0x8:64, el\]*}
    {movq %rdi, %cs:0x4(%rip)} {*\[0x8:64 + 0x4:64, el\]*}

    {movq %rax, %ds:(%rbp)} {*\[RBP, el\]*}
    {movq %rax, %ds:(%rbp,%rdx)} {*\[RBP + RDX, el\]*}
    {movq %rax, %ds:(%rbp,%rdx,2)} {*\[RBP + (RDX << 0x1:2), el\]*}
    {movq %rax, %ds:(%rbp,%rdx,4)} {*\[RBP + (RDX << 0x2:2), el\]*}
    {movq %rax, %ds:(%rbp,%rdx,8)} {*\[RBP + (RDX << 0x3:2), el\]*}
    {movq %rax, %ds:0x4(%rbp)} {*\[RBP + 0x4:64, el\]*}
    {movq %rax, %ds:0x4(%rbp,%rdx)} {*\[(RBP + RDX) + 0x4:64, el\]*}
    {movq %rax, %ds:0x4(%rbp,%rdx,2)} {*\[(RBP + (RDX << 0x1:2)) + 0x4:64, el\]*}
    {movq %rax, %ds:0x4(%rbp,%rdx,4)} {*\[(RBP + (RDX << 0x2:2)) + 0x4:64, el\]*}
    {movq %rax, %ds:0x4(%rbp,%rdx,8)} {*\[(RBP + (RDX << 0x3:2)) + 0x4:64, el\]*}
    {movq %rdi, %ds:(,%rax)} {*\[RAX, el\]*}
    {movq %rdi, %ds:(,%rax,2)} {*\[RAX << 0x1:2, el\]*}
    {movq %rdi, %ds:(,%rax,4)} {*\[RAX << 0x2:2, el\]*}
    {movq %rdi, %ds:(,%rax,8)} {*\[RAX << 0x3:2, el\]*}
    {movq %rdi, %ds:0x4(,%rax)} {*\[RAX + 0x4:64, el\]*}
    {movq %rdi, %ds:0x4(,%rax,2)} {*\[(RAX << 0x1:2) + 0x4:64, el\]*}
    {movq %rdi, %ds:0x4(,%rax,4)} {*\[(RAX << 0x2:2) + 0x4:64, el\]*}
    {movq %rdi, %ds:0x4(,%rax,8)} {*\[(RAX << 0x3:2) + 0x4:64, el\]*}
    {movq %rdi, %ds:(%rip)} {*\[0x8:64, el\]*}
    {movq %rdi, %ds:0x4(%rip)} {*\[0x8:64 + 0x4:64, el\]*}

    {movq %rax, %es:(%rbp)} {*\[RBP, el\]*}
    {movq %rax, %es:(%rbp,%rdx)} {*\[RBP + RDX, el\]*}
    {movq %rax, %es:(%rbp,%rdx,2)} {*\[RBP + (RDX << 0x1:2), el\]*}
    {movq %rax, %es:(%rbp,%rdx,4)} {*\[RBP + (RDX << 0x2:2), el\]*}
    {movq %rax, %es:(%rbp,%rdx,8)} {*\[RBP + (RDX << 0x3:2), el\]*}
    {movq %rax, %es:0x4(%rbp)} {*\[RBP + 0x4:64, el\]*}
    {movq %rax, %es:0x4(%rbp,%rdx)} {*\[(RBP + RDX) + 0x4:64, el\]*}
    {movq %rax, %es:0x4(%rbp,%rdx,2)} {*\[(RBP + (RDX << 0x1:2)) + 0x4:64, el\]*}
    {movq %rax, %es:0x4(%rbp,%rdx,4)} {*\[(RBP + (RDX << 0x2:2)) + 0x4:64, el\]*}
    {movq %rax, %es:0x4(%rbp,%rdx,8)} {*\[(RBP + (RDX << 0x3:2)) + 0x4:64, el\]*}
    {movq %rdi, %es:(,%rax)} {*\[RAX, el\]*}
    {movq %rdi, %es:(,%rax,2)} {*\[RAX << 0x1:2, el\]*}
    {movq %rdi, %es:(,%rax,4)} {*\[RAX << 0x2:2, el\]*}
    {movq %rdi, %es:(,%rax,8)} {*\[RAX << 0x3:2, el\]*}
    {movq %rdi, %es:0x4(,%rax)} {*\[RAX + 0x4:64, el\]*}
    {movq %rdi, %es:0x4(,%rax,2)} {*\[(RAX << 0x1:2) + 0x4:64, el\]*}
    {movq %rdi, %es:0x4(,%rax,4)} {*\[(RAX << 0x2:2) + 0x4:64, el\]*}
    {movq %rdi, %es:0x4(,%rax,8)} {*\[(RAX << 0x3:2) + 0x4:64, el\]*}
    {movq %rdi, %es:(%rip)} {*\[0x8:64, el\]*}
    {movq %rdi, %es:0x4(%rip)} {*\[0x8:64 + 0x4:64, el\]*}

    {movq %rax, %ss:(%rbp)} {*\[RBP, el\]*}
    {movq %rax, %ss:(%rbp,%rdx)} {*\[RBP + RDX, el\]*}
    {movq %rax, %ss:(%rbp,%rdx,2)} {*\[RBP + (RDX << 0x1:2), el\]*}
    {movq %rax, %ss:(%rbp,%rdx,4)} {*\[RBP + (RDX << 0x2:2), el\]*}
    {movq %rax, %ss:(%rbp,%rdx,8)} {*\[RBP + (RDX << 0x3:2), el\]*}
    {movq %rax, %ss:0x4(%rbp)} {*\[RBP + 0x4:64, el\]*}
    {movq %rax, %ss:0x4(%rbp,%rdx)} {*\[(RBP + RDX) + 0x4:64, el\]*}
    {movq %rax, %ss:0x4(%rbp,%rdx,2)} {*\[(RBP + (RDX << 0x1:2)) + 0x4:64, el\]*}
    {movq %rax, %ss:0x4(%rbp,%rdx,4)} {*\[(RBP + (RDX << 0x2:2)) + 0x4:64, el\]*}
    {movq %rax, %ss:0x4(%rbp,%rdx,8)} {*\[(RBP + (RDX << 0x3:2)) + 0x4:64, el\]*}
    {movq %rdi, %ss:(,%rax)} {*\[RAX, el\]*}
    {movq %rdi, %ss:(,%rax,2)} {*\[RAX << 0x1:2, el\]*}
    {movq %rdi, %ss:(,%rax,4)} {*\[RAX << 0x2:2, el\]*}
    {movq %rdi, %ss:(,%rax,8)} {*\[RAX << 0x3:2, el\]*}
    {movq %rdi, %ss:0x4(,%rax)} {*\[RAX + 0x4:64, el\]*}
    {movq %rdi, %ss:0x4(,%rax,2)} {*\[(RAX << 0x1:2) + 0x4:64, el\]*}
    {movq %rdi, %ss:0x4(,%rax,4)} {*\[(RAX << 0x2:2) + 0x4:64, el\]*}
    {movq %rdi, %ss:0x4(,%rax,8)} {*\[(RAX << 0x3:2) + 0x4:64, el\]*}
    {movq %rdi, %ss:(%rip)} {*\[0x8:64, el\]*}
    {movq %rdi, %ss:0x4(%rip)} {*\[0x8:64 + 0x4:64, el\]*}
}

set suite(x86) {
    {movl %eax, 0x4} {*\[0x4:32, el\]*}
    {movl %eax, (%ebp)} {*\[EBP, el\]*}
    {movl %eax, (%ebp,%edx)} {*\[EBP + EDX, el\]*}
    {movl %eax, (%ebp,%edx,2)} {*\[EBP + (EDX << 0x1:2), el\]*}
    {movl %eax, (%ebp,%edx,4)} {*\[EBP + (EDX << 0x2:2), el\]*}
    {movl %eax, (%ebp,%edx,8)} {*\[EBP + (EDX << 0x3:2), el\]*}
    {movl %eax, 0x4(%ebp)} {*\[EBP + 0x4:32, el\]*}
    {movl %eax, 0x4(%ebp,%edx)} {*\[(EBP + EDX) + 0x4:32, el\]*}
    {movl %eax, 0x4(%ebp,%edx,2)} {*\[(EBP + (EDX << 0x1:2)) + 0x4:32, el\]*}
    {movl %eax, 0x4(%ebp,%edx,4)} {*\[(EBP + (EDX << 0x2:2)) + 0x4:32, el\]*}
    {movl %eax, 0x4(%ebp,%edx,8)} {*\[(EBP + (EDX << 0x3:2)) + 0x4:32, el\]*}
    {movl %edi, (,%eax)} {*\[EAX, el\]*}
    {movl %edi, (,%eax,2)} {*\[EAX << 0x1:2, el\]*}
    {movl %edi, (,%eax,4)} {*\[EAX << 0x2:2, el\]*}
    {movl %edi, (,%eax,8)} {*\[EAX << 0x3:2, el\]*}
    {movl %edi, 0x4(,%eax)} {*\[EAX + 0x4:32, el\]*}
    {movl %edi, 0x4(,%eax,2)} {*\[(EAX << 0x1:2) + 0x4:32, el\]*}
    {movl %edi, 0x4(,%eax,4)} {*\[(EAX << 0x2:2) + 0x4:32, el\]*}
    {movl %edi, 0x4(,%eax,8)} {*\[(EAX << 0x3:2) + 0x4:32, el\]*}

    {movl %eax, %fs:(%ebp)} {*\[FS_BASE + EBP, el\]*}
    {movl %eax, %fs:(%ebp,%edx)} {*\[FS_BASE + (EBP + EDX), el\]*}
    {movl %eax, %fs:(%ebp,%edx,2)} {*\[FS_BASE + (EBP + (EDX << 0x1:2)), el\]*}
    {movl %eax, %fs:(%ebp,%edx,4)} {*\[FS_BASE + (EBP + (EDX << 0x2:2)), el\]*}
    {movl %eax, %fs:(%ebp,%edx,8)} {*\[FS_BASE + (EBP + (EDX << 0x3:2)), el\]*}
    {movl %eax, %fs:0x4(%ebp)} {*\[FS_BASE + (EBP + 0x4:32), el\]*}
    {movl %eax, %fs:0x4(%ebp,%edx)} {*\[FS_BASE + ((EBP + EDX) + 0x4:32), el\]*}
    {movl %eax, %fs:0x4(%ebp,%edx,2)} {*\[FS_BASE + ((EBP + (EDX << 0x1:2)) + 0x4:32), el\]*}
    {movl %eax, %fs:0x4(%ebp,%edx,4)} {*\[FS_BASE + ((EBP + (EDX << 0x2:2)) + 0x4:32), el\]*}
    {movl %eax, %fs:0x4(%ebp,%edx,8)} {*\[FS_BASE + ((EBP + (EDX << 0x3:2)) + 0x4:32), el\]*}
    {movl %edi, %fs:(,%eax)} {*\[FS_BASE + EAX, el\]*}
    {movl %edi, %fs:(,%eax,2)} {*\[FS_BASE + (EAX << 0x1:2), el\]*}
    {movl %edi, %fs:(,%eax,4)} {*\[FS_BASE + (EAX << 0x2:2), el\]*}
    {movl %edi, %fs:(,%eax,8)} {*\[FS_BASE + (EAX << 0x3:2), el\]*}
    {movl %edi, %fs:0x4(,%eax)} {*\[FS_BASE + (EAX + 0x4:32), el\]*}
    {movl %edi, %fs:0x4(,%eax,2)} {*\[FS_BASE + ((EAX << 0x1:2) + 0x4:32), el\]*}
    {movl %edi, %fs:0x4(,%eax,4)} {*\[FS_BASE + ((EAX << 0x2:2) + 0x4:32), el\]*}
    {movl %edi, %fs:0x4(,%eax,8)} {*\[FS_BASE + ((EAX << 0x3:2) + 0x4:32), el\]*}

    {movl %eax, %gs:(%ebp)} {*\[GS_BASE + EBP, el\]*}
    {movl %eax, %gs:(%ebp,%edx)} {*\[GS_BASE + (EBP + EDX), el\]*}
    {movl %eax, %gs:(%ebp,%edx,2)} {*\[GS_BASE + (EBP + (EDX << 0x1:2)), el\]*}
    {movl %eax, %gs:(%ebp,%edx,4)} {*\[GS_BASE + (EBP + (EDX << 0x2:2)), el\]*}
    {movl %eax, %gs:(%ebp,%edx,8)} {*\[GS_BASE + (EBP + (EDX << 0x3:2)), el\]*}
    {movl %eax, %gs:0x4(%ebp)} {*\[GS_BASE + (EBP + 0x4:32), el\]*}
    {movl %eax, %gs:0x4(%ebp,%edx)} {*\[GS_BASE + ((EBP + EDX) + 0x4:32), el\]*}
    {movl %eax, %gs:0x4(%ebp,%edx,2)} {*\[GS_BASE + ((EBP + (EDX << 0x1:2)) + 0x4:32), el\]*}
    {movl %eax, %gs:0x4(%ebp,%edx,4)} {*\[GS_BASE + ((EBP + (EDX << 0x2:2)) + 0x4:32), el\]*}
    {movl %eax, %gs:0x4(%ebp,%edx,8)} {*\[GS_BASE + ((EBP + (EDX << 0x3:2)) + 0x4:32), el\]*}
    {movl %edi, %gs:(,%eax)} {*\[GS_BASE + EAX, el\]*}
    {movl %edi, %gs:(,%eax,2)} {*\[GS_BASE + (EAX << 0x1:2), el\]*}
    {movl %edi, %gs:(,%eax,4)} {*\[GS_BASE + (EAX << 0x2:2), el\]*}
    {movl %edi, %gs:(,%eax,8)} {*\[GS_BASE + (EAX << 0x3:2), el\]*}
    {movl %edi, %gs:0x4(,%eax)} {*\[GS_BASE + (EAX + 0x4:32), el\]*}
    {movl %edi, %gs:0x4(,%eax,2)} {*\[GS_BASE + ((EAX << 0x1:2) + 0x4:32), el\]*}
    {movl %edi, %gs:0x4(,%eax,4)} {*\[GS_BASE + ((EAX << 0x2:2) + 0x4:32), el\]*}
    {movl %edi, %gs:0x4(,%eax,8)} {*\[GS_BASE + ((EAX << 0x3:2) + 0x4:32), el\]*}

    {movl %eax, %cs:(%ebp)} {*\[EBP, el\]*}
    {movl %eax, %cs:(%ebp,%edx)} {*\[EBP + EDX, el\]*}
    {movl %eax, %cs:(%ebp,%edx,2)} {*\[EBP + (EDX << 0x1:2), el\]*}
    {movl %eax, %cs:(%ebp,%edx,4)} {*\[EBP + (EDX << 0x2:2), el\]*}
    {movl %eax, %cs:(%ebp,%edx,8)} {*\[EBP + (EDX << 0x3:2), el\]*}
    {movl %eax, %cs:0x4(%ebp)} {*\[EBP + 0x4:32, el\]*}
    {movl %eax, %cs:0x4(%ebp,%edx)} {*\[(EBP + EDX) + 0x4:32, el\]*}
    {movl %eax, %cs:0x4(%ebp,%edx,2)} {*\[(EBP + (EDX << 0x1:2)) + 0x4:32, el\]*}
    {movl %eax, %cs:0x4(%ebp,%edx,4)} {*\[(EBP + (EDX << 0x2:2)) + 0x4:32, el\]*}
    {movl %eax, %cs:0x4(%ebp,%edx,8)} {*\[(EBP + (EDX << 0x3:2)) + 0x4:32, el\]*}
    {movl %edi, %cs:(,%eax)} {*\[EAX, el\]*}
    {movl %edi, %cs:(,%eax,2)} {*\[EAX << 0x1:2, el\]*}
    {movl %edi, %cs:(,%eax,4)} {*\[EAX << 0x2:2, el\]*}
    {movl %edi, %cs:(,%eax,8)} {*\[EAX << 0x3:2, el\]*}
    {movl %edi, %cs:0x4(,%eax)} {*\[EAX + 0x4:32, el\]*}
    {movl %edi, %cs:0x4(,%eax,2)} {*\[(EAX << 0x1:2) + 0x4:32, el\]*}
    {movl %edi, %cs:0x4(,%eax,4)} {*\[(EAX << 0x2:2) + 0x4:32, el\]*}
    {movl %edi, %cs:0x4(,%eax,8)} {*\[(EAX << 0x3:2) + 0x4:32, el\]*}

    {movl %eax, %ds:(%ebp)} {*\[EBP, el\]*}
    {movl %eax, %ds:(%ebp,%edx)} {*\[EBP + EDX, el\]*}
    {movl %eax, %ds:(%ebp,%edx,2)} {*\[EBP + (EDX << 0x1:2), el\]*}
    {movl %eax, %ds:(%ebp,%edx,4)} {*\[EBP + (EDX << 0x2:2), el\]*}
    {movl %eax, %ds:(%ebp,%edx,8)} {*\[EBP + (EDX << 0x3:2), el\]*}
    {movl %eax, %ds:0x4(%ebp)} {*\[EBP + 0x4:32, el\]*}
    {movl %eax, %ds:0x4(%ebp,%edx)} {*\[(EBP + EDX) + 0x4:32, el\]*}
    {movl %eax, %ds:0x4(%ebp,%edx,2)} {*\[(EBP + (EDX << 0x1:2)) + 0x4:32, el\]*}
    {movl %eax, %ds:0x4(%ebp,%edx,4)} {*\[(EBP + (EDX << 0x2:2)) + 0x4:32, el\]*}
    {movl %eax, %ds:0x4(%ebp,%edx,8)} {*\[(EBP + (EDX << 0x3:2)) + 0x4:32, el\]*}
    {movl %edi, %ds:(,%eax)} {*\[EAX, el\]*}
    {movl %edi, %ds:(,%eax,2)} {*\[EAX << 0x1:2, el\]*}
    {movl %edi, %ds:(,%eax,4)} {*\[EAX << 0x2:2, el\]*}
    {movl %edi, %ds:(,%eax,8)} {*\[EAX << 0x3:2, el\]*}
    {movl %edi, %ds:0x4(,%eax)} {*\[EAX + 0x4:32, el\]*}
    {movl %edi, %ds:0x4(,%eax,2)} {*\[(EAX << 0x1:2) + 0x4:32, el\]*}
    {movl %edi, %ds:0x4(,%eax,4)} {*\[(EAX << 0x2:2) + 0x4:32, el\]*}
    {movl %edi, %ds:0x4(,%eax,8)} {*\[(EAX << 0x3:2) + 0x4:32, el\]*}

    {movl %eax, %es:(%ebp)} {*\[EBP, el\]*}
    {movl %eax, %es:(%ebp,%edx)} {*\[EBP + EDX, el\]*}
    {movl %eax, %es:(%ebp,%edx,2)} {*\[EBP + (EDX << 0x1:2), el\]*}
    {movl %eax, %es:(%ebp,%edx,4)} {*\[EBP + (EDX << 0x2:2), el\]*}
    {movl %eax, %es:(%ebp,%edx,8)} {*\[EBP + (EDX << 0x3:2), el\]*}
    {movl %eax, %es:0x4(%ebp)} {*\[EBP + 0x4:32, el\]*}
    {movl %eax, %es:0x4(%ebp,%edx)} {*\[(EBP + EDX) + 0x4:32, el\]*}
    {movl %eax, %es:0x4(%ebp,%edx,2)} {*\[(EBP + (EDX << 0x1:2)) + 0x4:32, el\]*}
    {movl %eax, %es:0x4(%ebp,%edx,4)} {*\[(EBP + (EDX << 0x2:2)) + 0x4:32, el\]*}
    {movl %eax, %es:0x4(%ebp,%edx,8)} {*\[(EBP + (EDX << 0x3:2)) + 0x4:32, el\]*}
    {movl %edi, %es:(,%eax)} {*\[EAX, el\]*}
    {movl %edi, %es:(,%eax,2)} {*\[EAX << 0x1:2, el\]*}
    {movl %edi, %es:(,%eax,4)} {*\[EAX << 0x2:2, el\]*}
    {movl %edi, %es:(,%eax,8)} {*\[EAX << 0x3:2, el\]*}
    {movl %edi, %es:0x4(,%eax)} {*\[EAX + 0x4:32, el\]*}
    {movl %edi, %es:0x4(,%eax,2)} {*\[(EAX << 0x1:2) + 0x4:32, el\]*}
    {movl %edi, %es:0x4(,%eax,4)} {*\[(EAX << 0x2:2) + 0x4:32, el\]*}
    {movl %edi, %es:0x4(,%eax,8)} {*\[(EAX << 0x3:2) + 0x4:32, el\]*}

    {movl %eax, %ss:(%ebp)} {*\[EBP, el\]*}
    {movl %eax, %ss:(%ebp,%edx)} {*\[EBP + EDX, el\]*}
    {movl %eax, %ss:(%ebp,%edx,2)} {*\[EBP + (EDX << 0x1:2), el\]*}
    {movl %eax, %ss:(%ebp,%edx,4)} {*\[EBP + (EDX << 0x2:2), el\]*}
    {movl %eax, %ss:(%ebp,%edx,8)} {*\[EBP + (EDX << 0x3:2), el\]*}
    {movl %eax, %ss:0x4(%ebp)} {*\[EBP + 0x4:32, el\]*}
    {movl %eax, %ss:0x4(%ebp,%edx)} {*\[(EBP + EDX) + 0x4:32, el\]*}
    {movl %eax, %ss:0x4(%ebp,%edx,2)} {*\[(EBP + (EDX << 0x1:2)) + 0x4:32, el\]*}
    {movl %eax, %ss:0x4(%ebp,%edx,4)} {*\[(EBP + (EDX << 0x2:2)) + 0x4:32, el\]*}
    {movl %eax, %ss:0x4(%ebp,%edx,8)} {*\[(EBP + (EDX << 0x3:2)) + 0x4:32, el\]*}
    {movl %edi, %ss:(,%eax)} {*\[EAX, el\]*}
    {movl %edi, %ss:(,%eax,2)} {*\[EAX << 0x1:2, el\]*}
    {movl %edi, %ss:(,%eax,4)} {*\[EAX << 0x2:2, el\]*}
    {movl %edi, %ss:(,%eax,8)} {*\[EAX << 0x3:2, el\]*}
    {movl %edi, %ss:0x4(,%eax)} {*\[EAX + 0x4:32, el\]*}
    {movl %edi, %ss:0x4(,%eax,2)} {*\[(EAX << 0x1:2) + 0x4:32, el\]*}
    {movl %edi, %ss:0x4(,%eax,4)} {*\[(EAX << 0x2:2) + 0x4:32, el\]*}
    {movl %edi, %ss:0x4(,%eax,8)} {*\[(EAX << 0x3:2) + 0x4:32, el\]*}
}

proc run {arch suite} {
    set encode "llvm-mc -arch=$arch --show-encoding"
    set extract  "awk -vFS=\"\[\" -vRS=\"\]\" '\{print \$2\}'"
    set mc "bap-mc --arch=$arch --show-insn=asm --x86-lifter=modern --show-bil=pretty"
    foreach {asm bil} $suite {
        set test "$arch.addressing.\[$asm\]"
        set command "echo '$asm' | $encode | $extract | $mc"
        spawn sh -c $command
        expect {
            "$asm$bil" { pass $test }
            default {
                puts $command
                fail $test
            }
        }
    }
}

foreach arch  [array names suite] {
    run $arch $suite($arch)
}

unset -nocomplain suite
