set test "veri-x86_64"

set tracesdir "veri/traces/x86-64"
set traces [exec ls $tracesdir]

set rules "veri/rules/x86_pin"

set skipped {  }
set known_mismatches { BSF BSR CPUID CMOV* NEG NOOP* RDTSC SYSCALL XGETBV }

proc is_match {insn patterns} {
    set r False
    foreach {pattern} $patterns {
        set x [string match $pattern $insn ]
        if [ string match $pattern $insn ] {
            set r True;
            break;
        }
    }
    return $r
}

foreach {trace} $traces {
    set file "$tracesdir/$trace"
    set insn [file rootname [file tail $trace]]
    if [is_match $insn $skipped] {
        puts "SKIP test for $insn"
    } else {
        match $file "--rules $rules" {
            "successed   | 100.00% " {pass "$test for $insn"}
            default {
                if [is_match $insn $known_mismatches] {
                    xfail "$test for $insn"
                } else { fail "verification failed for $insn" }
            }
        }
    }
}
